In [3]:
!pip install geopandas

Collecting geopandas
  Downloading https://files.pythonhosted.org/packages/f0/5d/916b7268ef551fa9647ce12220e9a68006374f1ce5b0ddaf1cd0df2880b7/geopandas-0.4.1-py2.py3-none-any.whl (922kB)
    100% |████████████████████████████████| 931kB 1.8MB/s ta 0:00:01
Collecting shapely (from geopandas)
  Downloading https://files.pythonhosted.org/packages/cf/f8/110690b7c44b9418f573e351084c23d33d782f84416bdb179f1b0f9f401c/Shapely-1.6.4.post2-cp36-cp36m-macosx_10_9_x86_64.whl (1.6MB)
    100% |████████████████████████████████| 1.6MB 481kB/s ta 0:00:01
Collecting pyproj (from geopandas)
  Downloading https://files.pythonhosted.org/packages/8c/c8/53f6ddaf96d3f1cfd3acfa8abdca585184eda3df30f28cf7a15baeb97b7b/pyproj-2.1.2-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (11.4MB)
    100% |████████████████████████████████| 11.4MB 1.5MB/s ta 0:00:011   79% |█████████████████████████▌      | 9.1MB 427kB/s eta 0:00:06
Requirement already satisfied: pandas in /anaconda3/envs/PythonData/lib/python3.6/site-packages (from geopandas) (0.23.4)
Collecting fiona (from geopandas)
  Downloading https://files.pythonhosted.org/packages/4e/5e/dd1c598b5574249f8ea22ae4224d445ef45e4b4bb919cd2388c31caf42b0/Fiona-1.8.6-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (24.6MB)
    100% |████████████████████████████████| 24.6MB 1.7MB/s eta 0:00:01
Requirement already satisfied: python-dateutil>=2.5.0 in /anaconda3/envs/PythonData/lib/python3.6/site-packages (from pandas->geopandas) (2.7.5)
Requirement already satisfied: pytz>=2011k in /anaconda3/envs/PythonData/lib/python3.6/site-packages (from pandas->geopandas) (2018.7)
Requirement already satisfied: numpy>=1.9.0 in /anaconda3/envs/PythonData/lib/python3.6/site-packages (from pandas->geopandas) (1.15.4)
Collecting munch (from fiona->geopandas)
  Downloading https://files.pythonhosted.org/packages/68/f4/260ec98ea840757a0da09e0ed8135333d59b8dfebe9752a365b04857660a/munch-2.3.2.tar.gz
Collecting click-plugins>=1.0 (from fiona->geopandas)
  Downloading https://files.pythonhosted.org/packages/95/dd/fef84cf1678418f241ef542c0288bdf215bdd3e35f1fe03dc5223a2e80ba/click_plugins-1.0.4-py2.py3-none-any.whl
Requirement already satisfied: six>=1.7 in /anaconda3/envs/PythonData/lib/python3.6/site-packages (from fiona->geopandas) (1.12.0)
Requirement already satisfied: attrs>=17 in /anaconda3/envs/PythonData/lib/python3.6/site-packages (from fiona->geopandas) (18.2.0)
Requirement already satisfied: click<8,>=4.0 in /anaconda3/envs/PythonData/lib/python3.6/site-packages (from fiona->geopandas) (7.0)
Collecting cligj>=0.5 (from fiona->geopandas)
  Downloading https://files.pythonhosted.org/packages/e4/be/30a58b4b0733850280d01f8bd132591b4668ed5c7046761098d665ac2174/cligj-0.5.0-py3-none-any.whl
Building wheels for collected packages: munch
  Running setup.py bdist_wheel for munch ... done
  Stored in directory: /Users/rjdgrona/Library/Caches/pip/wheels/db/bf/bc/06a3e1bfe0ab27d2e720ceb3cff3159398d92644c0cec2c125
Successfully built munch
Installing collected packages: shapely, pyproj, munch, click-plugins, cligj, fiona, geopandas
Successfully installed click-plugins-1.0.4 cligj-0.5.0 fiona-1.8.6 geopandas-0.4.1 munch-2.3.2 pyproj-2.1.2 shapely-1.6.4.post2

In [38]:
%matplotlib inline

import pandas as pd
import matplotlib.pyplot as plt
import geopandas as gpd
import numpy as np

In [39]:
adults_df = pd.read_csv("Resources/share-of-adults-who-are-overweight.csv")
adults_df = adults_df.dropna(how='any')
dates = [2010, 2011, 2012, 2013, 2014, 2015]
adults_df_2013 = adults_df[adults_df["Year"].isin(dates)]
# adults_df_2013 = adults_df.loc[adults_df["Year"] == 2013, :]
del adults_df_2013['Entity']
# del adults_df_2013['Year']
adults_df_2013 = adults_df_2013.rename(columns={"Indicator:Prevalence of overweight among adults, BMI &GreaterEqual; 25 (crude estimate) (%) - Age Group:18+  years - Sex:Both sexes (%)":"% Adults > 25BMI"})
adults_df_2013.head()
# adults_df_2013.columns

   Code  Year  % Adults > 25BMI
35  AFG  2010              16.7
36  AFG  2011              17.2
37  AFG  2012              17.6
38  AFG  2013              18.1
39  AFG  2014              18.6

In [40]:
cause_df = pd.read_csv("Resources/burden-of-disease-by-cause.csv")
cause_df = cause_df.dropna(how='any')
cause_df_2013 = cause_df[cause_df["Year"].isin(dates)]
del cause_df_2013['Entity']
# del cause_df_2013['Year']
cause_df_2013.head()
# cause_df_2013.columns

,Code,Year,HIV/AIDS and tuberculosis (DALYs),Diarrhea & common infectious diseases (DALYs),Malaria & neglected tropical diseases (DALYs),Maternal disorders (DALYs),Neonatal disorders (DALYs),Nutritional deficiencies (DALYs),Other communicable diseases (DALYs),Cancers (DALYs),...,Mental and substance use disorders (DALYs),"Diabetes, blood, & endocrine diseases (DALYs)",Musculoskeletal disorders (DALYs),Other NCDs (DALYs),Transport injuries (DALYs),Natural disasters (DALYs),Conflict and terrorism (DALYs),Self-harm (DALYs),Interpersonal violence (DALYs),Unintentional injuries (DALYs)
20,AFG,2010,577336.193250,4.520086e+06,273855.773545,288079.973047,1.876099e+06,194622.538574,196019.888662,549341.699598,...,567952.892791,742783.059933,334871.312651,1.360054e+06,735221.531246,24433.066362,6.387659e+05,90922.734250,290588.776996,724795.519947
21,AFG,2011,556862.311919,4.593755e+06,269694.256745,280599.414970,1.844074e+06,190949.485902,181530.606773,555134.523343,...,589829.942431,751911.877389,347341.666480,1.300501e+06,721572.339289,7445.206774,6.824123e+05,92927.719099,293776.605049,657100.057414
22,AFG,2012,543752.688987,4.410766e+06,274423.442709,276872.039201,1.845900e+06,192721.523763,182148.076439,571672.632814,...,614059.271202,778638.228748,362439.580531,1.325675e+06,740365.483976,23421.811997,6.967352e+05,96410.545054,303832.637501,663862.287871
23,AFG,2013,559159.736902,3.527351e+06,302079.587646,282475.205009,1.919800e+06,205793.584590,221179.138408,615582.241007,...,640738.068563,847821.593210,380193.163336,1.557879e+06,838282.394294,12059.273418,7.182511e+05,103157.339525,328380.481910,852112.586953
24,AFG,2014,557236.296833,3.226200e+06,313865.589116,283787.564921,1.956194e+06,211292.458089,235112.725576,643594.115850,...,667942.903293,892203.477224,397637.862815,1.642508e+06,881184.899355,38542.407865,1.003628e+06,107924.894785,343983.471826,913990.663272

In [41]:
men_bmi_file = "Resources/mean-body-mass-index-bmi-in-adult-males.csv"
men_bmi_df = pd.read_csv(men_bmi_file)
men_bmi_df = men_bmi_df.dropna(how='any')
men_bmi_df_2013 = men_bmi_df[men_bmi_df["Year"].isin(dates)]
del men_bmi_df_2013['Entity']
# del men_bmi_df_2013['Year']
del men_bmi_df_2013['Total population (Gapminder)']
men_bmi_df_2013.head()

    Code  Year    (kg/m2)
64   AFG  2010  21.306405
65   AFG  2011  21.371975
66   AFG  2012  21.442372
67   AFG  2013  21.508647
168  ALB  2010  26.240956

In [42]:
men_file = "Resources/share-of-adult-men-overweight-or-obese-vs-daily-supply-of-calories.csv"
men_df = pd.read_csv(men_file)
men_df = men_df.dropna(how='any')

men_df_2013 = men_df[men_df["Year"].isin(dates)]
men_df_2013.head()

,Entity,Code,Year,Daily caloric supply (per person) (kcal/person/day),Overweight or Obese (%),Total population (Gapminder)
64,Afghanistan,AFG,2010,2104.0,11.7,31411743.0
65,Afghanistan,AFG,2011,2107.0,12.1,32358260.0
66,Afghanistan,AFG,2012,2100.0,12.5,33397058.0
67,Afghanistan,AFG,2013,2090.0,12.9,34499915.0
221,Albania,ALB,2010,3076.0,54.8,3204284.0

In [43]:
merge_men_table = pd.merge(men_df_2013, men_bmi_df_2013, on=["Code", "Year"] , how="left")
merge_men_table.columns
merge_men_table = merge_men_table.rename(columns={" (kg/m2)":"Men (BMI)"})
merge_men_table = merge_men_table.rename(columns={"Overweight or Obese (%)":"Men Overweight or Obese (%)"})
merge_men_table.head()

,Entity,Code,Year,Daily caloric supply (per person) (kcal/person/day),Men Overweight or Obese (%),Total population (Gapminder),Men (BMI)
0,Afghanistan,AFG,2010,2104.0,11.7,31411743.0,21.306405
1,Afghanistan,AFG,2011,2107.0,12.1,32358260.0,21.371975
2,Afghanistan,AFG,2012,2100.0,12.5,33397058.0,21.442372
3,Afghanistan,AFG,2013,2090.0,12.9,34499915.0,21.508647
4,Albania,ALB,2010,3076.0,54.8,3204284.0,26.240956

In [44]:
women_bmi_file = "Resources/mean-body-mass-index-bmi-in-adult-women.csv"
women_bmi_df = pd.read_csv(women_bmi_file)
women_bmi_df = women_bmi_df.dropna(how='any')
women_bmi_df_2013 = women_bmi_df[women_bmi_df["Year"].isin(dates)]

del women_bmi_df_2013['Entity']
# del women_bmi_df_2013['Year']
del women_bmi_df_2013['Total population (Gapminder)']
women_bmi_df_2013.head()

    Code  Year    (kg/m2)
64   AFG  2010  23.136148
65   AFG  2011  23.273018
66   AFG  2012  23.413553
67   AFG  2013  23.549702
168  ALB  2010  25.606621

In [45]:
women_file = "Resources/share-of-adult-women-overweight-or-obese-vs-daily-caloric-supply.csv"
women_df = pd.read_csv(women_file)
women_df = women_df.dropna(how='any')
women_df_2013 = women_df[women_df["Year"].isin(dates)]
del women_df_2013['Entity']
# del women_df_2013['Year']
del women_df_2013['Daily caloric supply (per person) (kcal/person/day)']
del women_df_2013['Total population (Gapminder)']
women_df_2013.head()

    Code  Year  Share of women overweight or obese (%)
64   AFG  2010                                    17.6
65   AFG  2011                                    18.2
66   AFG  2012                                    18.9
67   AFG  2013                                    19.5
221  ALB  2010                                    44.2

In [46]:
merge_women_table = pd.merge(women_bmi_df_2013, women_df_2013, on=["Code", "Year"], how="left")
merge_women_table.columns
merge_women_table = merge_women_table.rename(columns={" (kg/m2)":"Women (BMI)"})
merge_women_table = merge_women_table.rename(columns={"Share of women overweight or obese (%)":"Women overweight or obese (%)"})
merge_women_table.head()

  Code  Year  Women (BMI)  Women overweight or obese (%)
0  AFG  2010    23.136148                           17.6
1  AFG  2011    23.273018                           18.2
2  AFG  2012    23.413553                           18.9
3  AFG  2013    23.549702                           19.5
4  ALB  2010    25.606621                           44.2

In [47]:
merge_table = pd.merge(merge_men_table, merge_women_table, on=["Code", "Year"], how="left")
merge_table = merge_table[["Entity","Code","Year",
                           "Men Overweight or Obese (%)",
                           "Men (BMI)",
                           "Women overweight or obese (%)",
                           "Women (BMI)",
                           "Daily caloric supply (per person) (kcal/person/day)",
                           "Total population (Gapminder)"]]
merge_table

,Entity,Code,Year,Men Overweight or Obese (%),Men (BMI),Women overweight or obese (%),Women (BMI),Daily caloric supply (per person) (kcal/person/day),Total population (Gapminder)
0,Afghanistan,AFG,2010,11.7,21.306405,17.6,23.136148,2104.0,31411743.0
1,Afghanistan,AFG,2011,12.1,21.371975,18.2,23.273018,2107.0,32358260.0
2,Afghanistan,AFG,2012,12.5,21.442372,18.9,23.413553,2100.0,33397058.0
3,Afghanistan,AFG,2013,12.9,21.508647,19.5,23.549702,2090.0,34499915.0
4,Albania,ALB,2010,54.8,26.240956,44.2,25.606621,3076.0,3204284.0
5,Albania,ALB,2011,55.8,26.320106,44.5,25.644327,3132.0,3215988.0
6,Albania,ALB,2012,56.7,26.395070,44.9,25.674644,3184.0,3227373.0
7,Albania,ALB,2013,57.5,26.464979,45.1,25.699533,3193.0,3238316.0
8,Algeria,DZA,2010,48.3,24.091221,59.2,25.800673,3142.0,35468208.0
9,Algeria,DZA,2011,49.1,24.135085,59.8,25.846943,3217.0,35980193.0
10,Algeria,DZA,2012,49.9,24.177627,60.3,25.893641,3272.0,36485828.0
11,Algeria,DZA,2013,50.7,24.218087,60.8,25.938751,3296.0,36983924.0
12,Angola,AGO,2010,15.9,22.426910,31.2,23.641859,2345.0,19081912.0
13,Angola,AGO,2011,16.6,22.523993,32.1,23.761181,2407.0,19618432.0
14,Angola,AGO,2012,17.3,22.613642,33.0,23.875018,2384.0,20162517.0
15,Angola,AGO,2013,18.0,22.696896,33.8,23.982417,2473.0,20714494.0
16,Antigua and Barbuda,ATG,2010,49.9,26.755169,63.4,28.683875,2316.0,88710.0
17,Antigua and Barbuda,ATG,2011,50.7,26.862506,64.0,28.797225,2369.0,89612.0
18,Antigua and Barbuda,ATG,2012,51.5,26.972355,64.6,28.913373,2293.0,90510.0
19,Antigua and Barbuda,ATG,2013,52.3,27.080538,65.2,29.029067,2417.0,91404.0
20,Argentina,ARG,2010,63.8,27.192914,57.5,26.851882,3155.0,40412376.0
21,Argentina,ARG,2011,64.6,27.298786,58.1,26.955600,3161.0,40764561.0
22,Argentina,ARG,2012,65.3,27.396247,58.7,27.054027,3197.0,41118986.0
23,Argentina,ARG,2013,66.0,27.488960,59.2,27.148180,3229.0,41473982.0
24,Armenia,ARM,2010,50.5,25.450012,51.1,27.088212,2768.0,3092072.0
25,Armenia,ARM,2011,51.7,25.561542,51.7,27.170246,2788.0,3100236.0
26,Armenia,ARM,2012,52.8,25.672537,52.2,27.250829,2882.0,3108972.0
27,Armenia,ARM,2013,53.9,25.779199,52.7,27.327950,2928.0,3117722.0
28,Australia,AUS,2010,67.4,27.316603,55.2,26.556773,3213.0,22268384.0
29,Australia,AUS,2011,67.9,27.363393,55.8,26.613055,3237.0,22605732.0
...,...,...,...,...,...,...,...,...,...
644,United States,USA,2012,71.9,28.788759,62.0,28.540576,3687.0,315791284.0
645,United States,USA,2013,72.3,28.861752,62.4,28.616881,3682.0,318497630.0
646,Uruguay,URY,2010,59.8,26.380930,58.2,26.667784,2984.0,3368786.0
647,Uruguay,URY,2011,60.6,26.492390,58.8,26.748746,3012.0,3380008.0
648,Uruguay,URY,2012,61.4,26.601268,59.4,26.830805,3016.0,3391428.0
649,Uruguay,URY,2013,62.1,26.709194,60.1,26.911255,3050.0,3403117.0
650,Uzbekistan,UZB,2010,43.5,25.313187,47.2,25.826820,2648.0,27444702.0
651,Uzbekistan,UZB,2011,44.3,25.424190,48.1,25.961008,2694.0,27760267.0
652,Uzbekistan,UZB,2012,45.1,25.535426,49.0,26.095353,2730.0,28077486.0
653,Uzbekistan,UZB,2013,46.0,25.647461,49.8,26.229530,2760.0,28398155.0
654,Vanuatu,VUT,2010,45.2,25.308110,58.5,26.473617,2856.0,239651.0
655,Vanuatu,VUT,2011,45.7,25.310571,59.1,26.539056,2841.0,245619.0
656,Vanuatu,VUT,2012,46.2,25.309740,59.8,26.604244,2818.0,251674.0
657,Vanuatu,VUT,2013,46.7,25.307579,60.4,26.668164,2836.0,257812.0
658,Venezuela,VEN,2010,59.4,26.976067,62.3,26.843385,2805.0,28979857.0
659,Venezuela,VEN,2011,60.1,27.053854,62.6,26.896766,2803.0,29436891.0
660,Venezuela,VEN,2012,60.9,27.134019,63.0,26.953367,2691.0,29890694.0
661,Venezuela,VEN,2013,61.6,27.210161,63.4,27.006821,2631.0,30340637.0
662,Vietnam,VNM,2010,12.7,20.850870,18.0,20.886288,2678.0,87848445.0
663,Vietnam,VNM,2011,13.4,20.933276,18.7,20.952053,2716.0,88791996.0
664,Vietnam,VNM,2012,14.2,21.011679,19.3,21.014191,2713.0,89730274.0
665,Vietnam,VNM,2013,15.0,21.087434,20.0,21.073543,2745.0,90656550.0
666,Zambia,ZMB,2010,16.7,21.088992,33.5,23.243800,1904.0,13088570.0
667,Zambia,ZMB,2011,17.1,21.147291,34.4,23.328122,1907.0,13474959.0
668,Zambia,ZMB,2012,17.6,21.205570,35.3,23.409798,1923.0,13883577.0
669,Zambia,ZMB,2013,18.0,21.263786,36.1,23.490086,1930.0,14314515.0
670,Zimbabwe,ZWE,2010,18.1,21.874450,46.9,24.847265,2168.0,12571454.0
671,Zimbabwe,ZWE,2011,18.4,21.889436,47.5,24.871325,2200.0,12754378.0
672,Zimbabwe,ZWE,2012,18.7,21.910570,48.2,24.900643,2197.0,13013678.0
673,Zimbabwe,ZWE,2013,19.1,21.933703,48.9,24.931636,2110.0,13327925.0

In [48]:
merge_table = pd.merge(merge_table, cause_df_2013, on=["Code", "Year"], how="left")
merge_table.head()

,Entity,Code,Year,Men Overweight or Obese (%),Men (BMI),Women overweight or obese (%),Women (BMI),Daily caloric supply (per person) (kcal/person/day),Total population (Gapminder),HIV/AIDS and tuberculosis (DALYs),...,Mental and substance use disorders (DALYs),"Diabetes, blood, & endocrine diseases (DALYs)",Musculoskeletal disorders (DALYs),Other NCDs (DALYs),Transport injuries (DALYs),Natural disasters (DALYs),Conflict and terrorism (DALYs),Self-harm (DALYs),Interpersonal violence (DALYs),Unintentional injuries (DALYs)
0,Afghanistan,AFG,2010,11.7,21.306405,17.6,23.136148,2104.0,31411743.0,577336.193250,...,567952.892791,742783.059933,334871.312651,1.360054e+06,735221.531246,24433.066362,638765.868135,90922.734250,290588.776996,724795.519947
1,Afghanistan,AFG,2011,12.1,21.371975,18.2,23.273018,2107.0,32358260.0,556862.311919,...,589829.942431,751911.877389,347341.666480,1.300501e+06,721572.339289,7445.206774,682412.283282,92927.719099,293776.605049,657100.057414
2,Afghanistan,AFG,2012,12.5,21.442372,18.9,23.413553,2100.0,33397058.0,543752.688987,...,614059.271202,778638.228748,362439.580531,1.325675e+06,740365.483976,23421.811997,696735.212957,96410.545054,303832.637501,663862.287871
3,Afghanistan,AFG,2013,12.9,21.508647,19.5,23.549702,2090.0,34499915.0,559159.736902,...,640738.068563,847821.593210,380193.163336,1.557879e+06,838282.394294,12059.273418,718251.148272,103157.339525,328380.481910,852112.586953
4,Albania,ALB,2010,54.8,26.240956,44.2,25.606621,3076.0,3204284.0,450.456954,...,51700.097852,34033.488667,66935.331310,7.937982e+04,19418.320293,74.865115,607.606417,9152.922465,4701.935587,40577.933813

In [49]:
merge_table = pd.merge(merge_table, adults_df_2013, on=["Code", "Year"], how="left")
merge_table.head()

,Entity,Code,Year,Men Overweight or Obese (%),Men (BMI),Women overweight or obese (%),Women (BMI),Daily caloric supply (per person) (kcal/person/day),Total population (Gapminder),HIV/AIDS and tuberculosis (DALYs),...,"Diabetes, blood, & endocrine diseases (DALYs)",Musculoskeletal disorders (DALYs),Other NCDs (DALYs),Transport injuries (DALYs),Natural disasters (DALYs),Conflict and terrorism (DALYs),Self-harm (DALYs),Interpersonal violence (DALYs),Unintentional injuries (DALYs),% Adults > 25BMI
0,Afghanistan,AFG,2010,11.7,21.306405,17.6,23.136148,2104.0,31411743.0,577336.193250,...,742783.059933,334871.312651,1.360054e+06,735221.531246,24433.066362,638765.868135,90922.734250,290588.776996,724795.519947,16.7
1,Afghanistan,AFG,2011,12.1,21.371975,18.2,23.273018,2107.0,32358260.0,556862.311919,...,751911.877389,347341.666480,1.300501e+06,721572.339289,7445.206774,682412.283282,92927.719099,293776.605049,657100.057414,17.2
2,Afghanistan,AFG,2012,12.5,21.442372,18.9,23.413553,2100.0,33397058.0,543752.688987,...,778638.228748,362439.580531,1.325675e+06,740365.483976,23421.811997,696735.212957,96410.545054,303832.637501,663862.287871,17.6
3,Afghanistan,AFG,2013,12.9,21.508647,19.5,23.549702,2090.0,34499915.0,559159.736902,...,847821.593210,380193.163336,1.557879e+06,838282.394294,12059.273418,718251.148272,103157.339525,328380.481910,852112.586953,18.1
4,Albania,ALB,2010,54.8,26.240956,44.2,25.606621,3076.0,3204284.0,450.456954,...,34033.488667,66935.331310,7.937982e+04,19418.320293,74.865115,607.606417,9152.922465,4701.935587,40577.933813,54.3

In [51]:
merge_table.to_csv("Output/cleaned_BMI_data.csv", index=False)